#!/bin/sh

OUTPUT_FILE=EE-Killfile-Greasemonkey.user.js
cat > $OUTPUT_FILE <<EOF
// ==UserScript==
// @name        EE-Killfile
// @namespace   noideawhatthisis
// @include     http://www.baseballthinkfactory.org/forums/viewthread/*
// @match       http://www.baseballthinkfactory.org/forums/viewthread/*
// @version     1
// @grant       none
// @description It blocks posts on the BTF fora.
// ==/UserScript==

configuration = new Array();
// EDIT THESE NEXT FOUR LINES!!!!!!!!!!
configuration['kill_regex'] = "default regex never matches nothing";
configuration['autoignore'] = true;
configuration['hide_images'] = true;
configuration['hide_fully'] = false;
window.addEventListener('load', run_killfile(configuration), true);

// The rest of this file is automatically generated by chrome_to_greasemonkey.sh
// and you probably don't want to edit it except for debugging. Edit the
// code in content_script.js and then run chrome_to_greasemonkey.sh again.
// Thanks to Joe Mauer Power Hour for leading the way.
EOF
cat content_script.js |
grep -v chrome.storage.sync >> $OUTPUT_FILE
