#!/bin/sh

OUTPUT_FILE=EE-Killfile-Greasemonkey.user.js
cat > $OUTPUT_FILE <<EOF
configuration = new Array();
configuration.configuration = new Array();
// EDIT THESE NEXT TWO LINES!!!!!!!!!!
configuration.configuration['kill_regex'] = "quote_author=.Yun Taragoashi";
configuration.configuration['autoignore'] = "true";
window.addEventListener('load', actually_do_things(configuration), true);

// The rest of this file is automatically generated by chrome_to_greasemonkey.sh
// and you probably don't want to edit it except for debugging. Edit the
// code in content_script.js and then run chrome_to_greasemonkey.sh again.
// Thanks to Joe Mauer Power Hour for leading the way.
EOF
cat content_script.js |
grep -v chrome.extension.sendRequest >> $OUTPUT_FILE
